# Generated by Django 4.1.2 on 2022-11-01 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['created_at'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AddField(
            model_name='post',
            name='date_event',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата события'),
        ),
    ]
