# Generated by Django 4.1.2 on 2022-11-05 16:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback_alter_post_date_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(choices=[('1', 'от 2 до 4 лет'), ('2', 'от 5 до 10 лет'), ('3', 'Ленинградское ш., 27, Дмитровское ш., 79'), ('4', 'Индивидуальная тренировка')], max_length=100, verbose_name='Группа')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('connection', models.CharField(choices=[('P', 'Телефонный звонок'), ('T', 'Telegram'), ('W', 'WhatsApp')], max_length=100, verbose_name='Связаться по')),
            ],
            options={
                'verbose_name': 'Заявка на абонимент',
                'verbose_name_plural': 'Заявка на абонимент',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
